"""create trend tables

Revision ID: c3c8a02dcfb8
Revises: 
Create Date: 2026-01-21 18:42:16.213632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c8a02dcfb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('trend_volume', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('keyword_collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('instagram_posts', sa.Integer(), nullable=True),
    sa.Column('youtube_videos', sa.Integer(), nullable=True),
    sa.Column('news_count', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_country'), 'keywords', ['country'], unique=False)
    op.create_index('ix_keywords_country_collected', 'keywords', ['country', 'keyword_collected_at'], unique=False)
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_index(op.f('ix_keywords_keyword'), 'keywords', ['keyword'], unique=False)
    op.create_table('instagram_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('keyword_country', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_index(op.f('ix_instagram_contents_id'), 'instagram_contents', ['id'], unique=False)
    op.create_index(op.f('ix_instagram_contents_keyword_id'), 'instagram_contents', ['keyword_id'], unique=False)
    op.create_table('news_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('keyword_country', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_contents_id'), 'news_contents', ['id'], unique=False)
    op.create_index(op.f('ix_news_contents_keyword_id'), 'news_contents', ['keyword_id'], unique=False)
    op.create_table('youtube_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('channel', sa.String(length=200), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('keyword_country', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_index(op.f('ix_youtube_contents_id'), 'youtube_contents', ['id'], unique=False)
    op.create_index(op.f('ix_youtube_contents_keyword_id'), 'youtube_contents', ['keyword_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_contents_keyword_id'), table_name='youtube_contents')
    op.drop_index(op.f('ix_youtube_contents_id'), table_name='youtube_contents')
    op.drop_table('youtube_contents')
    op.drop_index(op.f('ix_news_contents_keyword_id'), table_name='news_contents')
    op.drop_index(op.f('ix_news_contents_id'), table_name='news_contents')
    op.drop_table('news_contents')
    op.drop_index(op.f('ix_instagram_contents_keyword_id'), table_name='instagram_contents')
    op.drop_index(op.f('ix_instagram_contents_id'), table_name='instagram_contents')
    op.drop_table('instagram_contents')
    op.drop_index(op.f('ix_keywords_keyword'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_index('ix_keywords_country_collected', table_name='keywords')
    op.drop_index(op.f('ix_keywords_country'), table_name='keywords')
    op.drop_table('keywords')
    # ### end Alembic commands ###
